### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 5.1 สำหรับเดสก์ท็อป Windows
  description: Microsoft Application Virtualization Hosting 5.1 for Windows Desktops เป็นไปตามนโยบายวงจรการใช้งานแบบคงที่
  ms.date: 09/10/2020
  keywords: for Windows Desktops
name: Microsoft Application Virtualization Hosting 5.1 สำหรับเดสก์ท็อป Windows
summary: |+
  Microsoft Application Virtualization Hosting 5.1 for Windows Desktops เป็นไปตามนโยบายวงจรการใช้งาน [แบบคงที่](/lifecycle/policies/fixed)

  สิ่งนี้ใช้ได้กับรุ่นต่อไปนี้: for Windows Desktops

products:
  - windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
  - version: Original Release
    startDate: 11/01/2015
    endDate: 04/14/2026
content: |

  ## <a name="links"></a>ลิงก์ 
  * [ข้อมูลผลิตภัณฑ์](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)


  ## <a name="editions"></a>รุ่น 
  * for Windows Desktops