### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: Microsoft Forefront Client Security เป็นไปตามนโยบายวงจรการใช้งานแบบคงที่
  ms.date: 08/28/2020
  ms.openlocfilehash: 335ae81ffa4b7cb64352b19e7330765a4cac6c68
  ms.sourcegitcommit: 570c824dbe19150d37398333df7d2c416a51eac9
  ms.translationtype: HT
  ms.contentlocale: th-TH
  ms.lasthandoff: 08/28/2020
  ms.locfileid: "924275"
name: Microsoft Forefront Client Security
summary: >+
  Microsoft Forefront Client Security เป็นไปตามนโยบายวงจรการใช้งาน [แบบคงที่](/lifecycle/policies/fixed)


products:
- msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
- version: Original Release
  startDate: 08/02/2007
  endDate: 07/14/2015
content: "\n## <a name=\"links\"></a>ลิงก์ \n* [System Center Endpoint Protection](/lifecycle/products/microsoft-system-center-2012-endpoint-protection)\n\n> [!NOTE]\n> Forefront Client Security ได้หยุดให้บริการตั้งแต่วันที่ 14 กรกฎาคม ค.ศ. 2015 การอัปเดตข้อกำหนดของ Antimalware และ Antispyware จะไม่สามารถใช้ได้อีกต่อไปหลังจากสิ้นสุดการสนับสนุนสำหรับเวอร์ชันผลิตภัณฑ์ โปรดประเมิน System Center Endpoint Protection เป็นการทดแทน"
