### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: Microsoft Forefront Client Security เป็นไปตามนโยบายวงจรการใช้งานแบบคงที่
  ms.date: 08/28/2020
  ms.openlocfilehash: d85aea21441458397839241e74939536051397d4
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: th-TH
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4113428"
name: Microsoft Forefront Client Security
summary: >+
  Microsoft Forefront Client Security เป็นไปตามนโยบายวงจรการใช้งาน [แบบคงที่](/lifecycle/policies/fixed)


products:
- msc
policyType: fixed
supportDates:
  start: 2007-08-02T00:00:00.000-08:00
  extendedEnd: 2015-07-14T22:59:59.999-08:00
releases:
- version: Original Release
  startDate: 2007-08-02T00:00:00.000-08:00
  endDate: 2015-07-14T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>ลิงก์ \n* [System Center Endpoint Protection](/lifecycle/products/microsoft-system-center-2012-endpoint-protection)\n\n> [!NOTE]\n> Forefront Client Security ได้หยุดให้บริการตั้งแต่วันที่ 14 กรกฎาคม ค.ศ. 2015 การอัปเดตข้อกำหนดของ Antimalware และ Antispyware จะไม่สามารถใช้ได้อีกต่อไปหลังจากสิ้นสุดการสนับสนุนสำหรับเวอร์ชันผลิตภัณฑ์ โปรดประเมิน System Center Endpoint Protection เป็นการทดแทน"
