### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007 R3
  description: Microsoft System Center Configuration Manager 2007 R3 เป็นไปตามนโยบายวงจรการใช้งานแบบคงที่
  ms.date: 07/28/2020
  ms.openlocfilehash: d50d60946e57727b81d7b6ec1e5ffe1654a93acd5942474c07dd0b56141d7870
  ms.sourcegitcommit: 1c28c95e7a2b743cff45216da63f72ffbad026ed
  ms.translationtype: HT
  ms.contentlocale: th-TH
  ms.lasthandoff: 08/06/2021
  ms.locfileid: "2523433"
name: Microsoft System Center Configuration Manager 2007 R3
summary: >
  Microsoft System Center Configuration Manager 2007 R3 เป็นไปตามนโยบายวงจรการใช้งาน [แบบคงที่](/lifecycle/policies/fixed)



  > [!IMPORTANT]

  > การสนับสนุนผลิตภัณฑ์นี้สิ้นสุดลงแล้ว ดูคำแนะนำในการย้ายข้อมูลด้านล่าง
products:
- msc
policyType: fixed
supportDates:
  start: 12/19/2010
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
- version: Original Release
  startDate: 12/19/2010
  endDate: 07/09/2019
content: "\n## <a name=\"links\"></a>ลิงก์ \n* [คำแนะนำในการย้ายข้อมูล](/mem/configmgr/core/migration/migrate-data-between-hierarchies)\n* [คำแนะนำการย้ายข้อมูลเพิ่มเติม](/mem/configmgr/core/migration/planning-for-migration)"
