### YamlMime:Lifecycle
metadata:
  title: ความปลอดภัยของไคลเอ็นต์ Microsoft Forefront
  description: ความปลอดภัยของไคลเอ็นต์ Microsoft Forefront ต่อไปนี้นโยบายวัฏจักรที่คงที่
  ms.date: 08/28/2020
  ms.openlocfilehash: 335ae81ffa4b7cb64352b19e7330765a4cac6c68
  ms.sourcegitcommit: 570c824dbe19150d37398333df7d2c416a51eac9
  ms.translationtype: MT
  ms.contentlocale: th-TH
  ms.lasthandoff: 08/28/2020
  ms.locfileid: "924275"
name: ความปลอดภัยของไคลเอ็นต์ Microsoft Forefront
summary: >+
  ความปลอดภัยของไคลเอ็นต์ Microsoft Forefront ต่อไปนี้นโยบายวัฏจักรที่ [คง](/lifecycle/policies/fixed) ที่


products:
- msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
- version: Original Release
  startDate: 08/02/2007
  endDate: 07/14/2015
content: "\n## <a name=\"links\"></a>ลิงก์ \n* [การป้องกันจุดสิ้นสุดของศูนย์ระบบ](/lifecycle/products/microsoft-system-center-2012-endpoint-protection)\n\n> [!NOTE]\n> การรักษาความปลอดภัยของไคลเอ็นต์ Forefront ถูกยกเลิกเมื่อวันที่14กรกฎาคม๒๐๑๕ การอัปเดตคำนิยาม Antimalware และป้องกันสปายแวร์จะไม่พร้อมใช้งานอีกต่อไปหลังจากสิ้นสุดการสนับสนุนสำหรับเวอร์ชันผลิตภัณฑ์ โปรดประเมินการป้องกันจุดสิ้นสุดของศูนย์กลางระบบเป็นการแทนที่"
